### ISSUE TITLE
about ExecuteRemoteCode

### ISSUE THREAD

**Issue by piyanggoon** [Dramacydal/WhiteMagic#2]
in this function, i think want asking for free memory after execute.

**Comment by Dramacydal** [comment]
Isn't it freed?
https://github.com/Dramacydal/WhiteMagic/blob/e497d038fc0a4a891cbe2890bf268fa05ee5c8a5/WhiteMagic/MemoryHandler.cs#L403

**Comment by piyanggoon** [comment]
Sometimes the FreeMemory() function caused a crash of the process. It would be better to have a boolean argument to free the memory or not
